# Generated by Django 3.0.2 on 2020-02-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prof_name', models.CharField(default='승호', max_length=30)),
                ('class_type', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=500)),
                ('recommend_year', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('hash_tags', models.CharField(default="['해쉬', '스완', '창모']", max_length=300)),
                ('attendance', models.CharField(max_length=100, null=True)),
                ('score_stlict', models.CharField(max_length=100, null=True)),
                ('homework', models.CharField(max_length=100, null=True)),
                ('teamplay', models.CharField(max_length=100, null=True)),
                ('test_time', models.CharField(max_length=100, null=True)),
                ('positive', models.CharField(max_length=100, null=True)),
                ('negative', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('hash_tags', models.CharField(max_length=300)),
                ('attendance', models.CharField(max_length=300)),
                ('score', models.CharField(max_length=100, null=True)),
                ('score_stlict', models.CharField(max_length=300)),
                ('homework', models.CharField(max_length=300)),
                ('teamplay', models.CharField(max_length=300)),
                ('test_time', models.CharField(max_length=300)),
                ('positive', models.CharField(max_length=100, null=True)),
                ('negative', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='search.Prof')),
                ('similar_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='search.Prof')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='search.Lecture')),
                ('similar_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='search.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='prof',
            name='similar_profs',
            field=models.ManyToManyField(blank=True, related_name='_prof_similar_profs_+', through='search.SimilarProf', to='search.Prof'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='prof',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='search.Prof'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='similar_lectures',
            field=models.ManyToManyField(blank=True, related_name='_lecture_similar_lectures_+', through='search.SimilarLecture', to='search.Lecture'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('name', 'prof', 'time')},
        ),
    ]
