# Generated by Django 3.0.2 on 2020-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200207_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='prof_name',
            field=models.CharField(default='승호', max_length=300),
        ),
    ]
