# Generated by Django 3.0.2 on 2020-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200207_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='class_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='prof_name',
            field=models.CharField(default='승호', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='prof',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
