# Generated by Django 3.0.2 on 2020-02-15 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200212_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_icons', to='search.Icon'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_icons', to='search.Icon'),
        ),
    ]
