# Generated by Django 3.0.2 on 2020-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200215_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
